version: '3.5'

services:
  
  sample-app:
    container_name: sample-app
    image: momojunzi/baguaclient:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
